### ISSUE TITLE
No support for macOS Version: 14.3.1, Architecture: x86_64

### ISSUE THREAD

**Issue by praveenvinny** [davesc63/GeoPort#1]
When I try to run the app in macOS Version: 14.3.1, Architecture: x86_64, it throws the following error:

```
sudo: unable to execute ./GeoPort: Bad CPU type in executable
```

I gave the complete access rights and tried to run the file as a root user. Here are the details:

```
praveen.vinny@sanya Desktop % echo "macOS Version: $(sw_vers -productVersion), Architecture: $(uname -m)"
macOS Version: 14.3.1, Architecture: x86_64

praveen.vinny@sanya Desktop % cd ./GeoPort-mac-12032024

praveen.vinny@sanya GeoPort-mac-12032024 % ls -l
total 56152
-rwxr-xr-x@ 1 praveen.vinny  staff  28743424 12 Mar 16:12 GeoPort
-rwxr-xr-x@ 1 praveen.vinny  staff        98 11 Mar 15:12 run.sh

praveen.vinny@sanya GeoPort-mac-12032024 % chmod a+x GeoPort

praveen.vinny@sanya GeoPort-mac-12032024 % sudo ./GeoPort
Password:
sudo: unable to execute ./GeoPort: Bad CPU type in executable
```

**Comment by praveenvinny** [comment]
However I can create a tunnel using the following command:

```
sudo python3 -m pymobiledevice3 remote start-tunnel
```

and then I can set the location using the following command:
```
sudo python3 -m pymobiledevice3 developer dvt simulate-location set --rsd fd83:4acd:ddaa::1 62648 -- -33.4182306 149.6015676
```

where ⁠ `-33.4182306` `149.6015676` ⁠ is the location for `Kelso, NSW`.

**Comment by davesc63** [comment]
Thanks @praveenvinny - The pyinstaller bundle hasn't been built to support Mac Intel architecture. I will work on getting one built asap

**Comment by davesc63** [comment]
Hi @praveenvinny - I have packaged an Intel Mac architecture version but haven't been able to test it (I don't have physical access to the build machine)

Please check it out if you can: https://github.com/davesc63/GeoPort/releases/download/beta/GeoPort-mac-x86-13032024.zip

**Comment by praveenvinny** [comment]
Cheers mate! `POST /connect_device` was initially failing. But it was able to create the tunnel once I logged in as the root user. I can confirm that the location has changed in the phone and I was able to see the changes in Apple Maps. Thank you.

**Comment by davesc63** [comment]
> Cheers mate! `POST /connect_device` was initially failing. But it was able to create the tunnel once I logged in as the root user. I can confirm that the location has changed in the phone and I was able to see the changes in Apple Maps. Thank you.

Awesome! Thanks for trying out GeoPort!
As you’ve found out, sudo is required to create the tunnel for iOS17. 

I’ll add a pop up notification to let people know
