### ISSUE TITLE
when disconnected from  laptop, location gets resetted to real location 

### ISSUE THREAD

**Issue by lucaSyntax** [davesc63/GeoPort#100]

**Comment by davesc63** [comment]
more details please?
what ios version, how are your disconnecting?

**Comment by screamloud** [comment]
It is also happening with me. I am running iOS 18. I just close the browser and unplug the iPhone from the PC.

**Comment by mikajx** [comment]
Same here. I am running Ios 18 and the latest update of the app.

**Comment by Willxup** [comment]
same, ios18

**Comment by lucalauria98** [comment]
same iOS 18, seems like softwares like anyGO or similar softwares solved the problem

**Comment by davesc63** [comment]
Its by design in iOS 18.
It continually tries to update the location back to the internal device GPS settings. It cannot be overriden through software
Other chinese made softwares are using external bluetooth emulation which will also only work while "tethered" to the virtual bluetooth device
