### ISSUE TITLE
Error fetching device list

### ISSUE THREAD

**Issue by ZackHJ** [davesc63/GeoPort#103]
Running on (M1) MacOS 15.1 and iOS 18.1.
The device list is empty, when checked the console, it seems there's an error when fetching 'list_devices'.
The iPhone is connected via USB, and pairs correctly with my Mac.

When I tried other similar apps, they all work. The key difference I noticed is that they all request access to connected devices, and I see the permission popup window, but not with GeoPort. Could this be the reason?

![Screen Shot 2024-09-27 at 14 49 04 PM](https://github.com/user-attachments/assets/e4ab5a27-354c-42e8-9008-735bc174f7d4)

**Comment by davesc63** [comment]
Can you share the GeoPort console output. 
The issue seems to be happening earlier and instead of sending device information to the front end, we are receiving that “SetProhibted”

**Comment by ZackHJ** [comment]
> Can you share the GeoPort console output. The issue seems to be happening earlier and instead of sending device information to the front end, we are receiving that “SetProhibted”

![Screen Shot 2024-09-27 at 15 18 54 PM](https://github.com/user-attachments/assets/97881c79-ab94-49a7-96b8-b1c9da54d407)

**Comment by davesc63** [comment]
Is there more?
We are detecting the device as both usb connected and WiFi in that screenshot. 

There should be more below this. So far no issues to this point

**Comment by ZackHJ** [comment]
That's all. I updated the above screenshot after starting a new instance, that's the entire log.

**Comment by davesc63** [comment]
Hmm haven’t seen this before but looks like it’s halting / crashing. 

The next step is to list an array or connected devices, check / set developer mode. 

There really should be more output. 

In this latest screenshot it appears it’s all WiFi based. Focus on usb connection first

**Comment by ZackHJ** [comment]
I refreshed the list, and the USB connection showed up again in the Geoport console, but still nothing in the dropdown.

When you mentioned developer mode, is that a mode of the GeoPort program?

**Comment by davesc63** [comment]
Nah developer mode for the iOS device. 
Not sure what’s happening on your machine. Shutdown GeoPort completely and try again?

Move just reviewed and I see ~80-100 people using iOS 18.1 already with GeoPort

**Comment by ZackHJ** [comment]
Developer mode is on, I've been using sideloaded app without issues.

I should note that it works when I run GeoPort on Windows using the same phone, under both USB and wifi. Not sure why it isn't working on Mac.
