### ISSUE TITLE
Ubuntu - how to run as sudo/administator ?

### ISSUE THREAD

**Issue by TiredBeeYYB** [davesc63/GeoPort#106]
The Geoport executable is on the desktop. How do I run it as sudo?
I type
`./GeoPort `
into the terminal- it works, but gives me "Connection timeout" after like 30 second of "connecting, please wait".
I type
`sudo ./GeoPort`
it says "Cannot create directory. Permission denied" when trying to create a bunch of files, "Authorization required, but no authorization protocol specified" and "no method avilable to open localhost" (i have firefox)

**Comment by davesc63** [comment]
You need usbmuxd2
Good luck as it's challenging to compile and doesn't have full support for the usb control messages anyway
