### ISSUE TITLE
Ubuntu - no devices found after multiple attempts although the device was actually found?

### ISSUE THREAD

**Issue by TiredBeeYYB** [davesc63/GeoPort#107]
![log](https://github.com/user-attachments/assets/38226077-045f-469c-9013-98f78a7ed04a)

**Comment by TiredBeeYYB** [comment]
absolutely the same issue happens with the same log (no devices found) in macos monterey. since i cant update from ios 17.1, if you could fix this i will be forever gratefull

**Comment by davesc63** [comment]
You have different issues here.
Ubuntu will not work unless you have compiled your own usbmuxd, and the current ones available do not fully support communication with pymobiledevice. The issues are NOT the same
