### ISSUE TITLE
How to Keep iPhone Location Fixed After Disconnecting from Localhost or Closing MacBook?

### ISSUE THREAD

**Issue by elvanrffsecond** [davesc63/GeoPort#110]
How can I keep the location on my iPhone (ios 18) fixed when the device is no longer connected to localhost? In other words, the MacBook is closed, but I want my iPhone to remain at the simulated location. Whereas the iPhone location will revert back to the original once it is no longer connected.

**Comment by davesc63** [comment]
This is not possible under ios18
Apple have made sure the location from the device takes over when disconnected. It even overwrites simulated location automatically
