### ISSUE TITLE
Source code and license

### ISSUE THREAD

**Issue by victornpb** [davesc63/GeoPort#111]
I don't wanna be that guy, but currently this repo is violating the GPL license by not making source available

also kinda breaks the open source spirit for those who want to inspect the code and build it from source, specially since this requires a great deal of permissions to run

and me personally i'm just interested in adding a few features like making it navigate a route, and like bookmarks

**Comment by davesc63** [comment]
@victornpb GPL was there by default. We can delete that easily or change it

Quite simply, a lot of time and effort went into making GeoPort. I would like to monetize that, which is occurring very slowly through donations - just to feel like it was worth the effort. 

Once a goal is hit, it can be open sourced

I’ve had offers from a Chinese group who just want to slap their logo and charge users. That’s an alternative path this can take

**Comment by victornpb** [comment]
> GPL was there by default. We can delete that easily or change it

Unfortunately this is not how licensing works, both [Pymobiledevice3](https://github.com/doronz88/pymobiledevice3) and [iFakeLocation](https://github.com/master131/iFakeLocation) are distributed under GPL, which forces you to release your source code under the same GPL license.

**Comment by davesc63** [comment]
> > GPL was there by default. We can delete that easily or change it
> 
> Unfortunately this is not how licensing works, both [Pymobiledevice3](https://github.com/doronz88/pymobiledevice3) and [iFakeLocation](https://github.com/master131/iFakeLocation) are distributed under GPL, which forces you to release your source code under the same GPL license.

Well @victornpb, give yourself a pat on the back as you’ve probably ruined GeoPort for everyone

**Comment by jmswangit** [comment]
@davesc63 I think your attitude here is terrible. @victornpb didn’t “ruin” GeoPort for everyone, your inability or unwillingness to abide by GPL might end up ruining it, but that would be 100% your fault, Dave. I love the program and use it often, but you’re absolutely in the wrong here and I hope you’ll choose to recognize that and abide by the GPL. Otherwise, it just feels like you don’t respect the idea of open source. Either way, blaming someone for calling you on your BS is a really really bad look.

**Comment by hurricaneindianajones** [comment]
quite possibly the wildest response to licensing abuse i've ever seen... mfw @victornpb ruined geoport for everyone

![image](https://github.com/user-attachments/assets/58e33dec-56a8-43d1-8c6f-8321488f696a)

seriously deleting the gpl license from the project in response? not sure if alpha or beta behaviour

**Comment by alexdalat** [comment]
It's too bad there aren't more pymobiledevice3 projects out there. Anyway, https://github.com/alexdalat/ios-virtual-loc for anyone looking for something open source...

**Comment by Nightmaresuwu** [comment]
> I don't wanna be that guy, but currently this repo is violating the GPL license by not making source available
> 
> also kinda breaks the open source spirit for those who want to inspect the code and build it from source, specially since this requires a great deal of permissions to run
> 
> and me personally i'm just interested in adding a few features like making it navigate a route, and like bookmarks

dw i decompyled the shit and have the source

**Comment by Nightmaresuwu** [comment]
> It's too bad there aren't more pymobiledevice3 projects out there. Anyway, https://github.com/alexdalat/ios-virtual-loc for anyone looking for something open source...

anyway i decompyled this project lol : https://github.com/Nightmaresuwu/GeoPort-Decompyled
