### ISSUE TITLE
geoport is unavailable for ios18 

### ISSUE THREAD

**Issue by ShawnFan2** [davesc63/GeoPort#112]
could author make it available to ios 18? i would appreciate it very much

**Comment by ISuckAtGames2** [comment]
i have an iPhone 13 running the iOS 18.1 beta 4 and it works perfectly fine for me. what issues are you experiencing when attempting to use it on iOS 18?

**Comment by ShawnFan2** [comment]
> i have an iPhone 13 running the iOS 18.1 beta 4 and it works perfectly fine for me. what issues are you experiencing when attempting to use it on iOS 18?

i run it on my iphone15 pm and ios18.0.1 , it didn't work, and on my friend's iphone 15pro ios 17 it work
oh no , it works today, i'm sorry lol.

**Comment by ShawnFan2** [comment]
> i have an iPhone 13 running the iOS 18.1 beta 4 and it works perfectly fine for me. what issues are you experiencing when attempting to use it on iOS 18?
my phone is iphone15pm and system is ios 18.0.1, i can change my location but after about 2mins it becomes the real locating,it seems like that the phone is continue tracking if the position is right.

**Comment by ISuckAtGames2** [comment]
intriguing. i don’t have the iphone 15 so i wont be able to recreate this issue. are you seeing any errors in the console??

**Comment by smaca69** [comment]
Mine doesnt work either.  It doesnt show up in the device list even after I refresh
iOS 18.1.1

**Comment by davesc63** [comment]
iOS18 is supported
