### ISSUE TITLE
Not supported for iOS 18. Position changes are only temporary and then get reset.

### ISSUE THREAD

**Issue by chalitbkb** [davesc63/GeoPort#113]
@davesc63 
Not compatible with iOS 18. Normally, I use it with iOS 17, and it works well without any issues. After changing the location, when I unplug the cable from the computer to make it remember that location constantly, it works fine. But for iOS 18, after I change the location and want to unplug the cable just like I used to do on iOS 17, it resets my location. Typically, on iOS 17, even after unplugging, it would still remember the spoofed location all the time. So I think there's something that needs to be improved to make it work even when the cable is unplugged from the device.

**Comment by davesc63** [comment]
@chalitbkb just to be clear. GeoPort does work on ios18

You issue has been answered a few times now. Ios18 resets to the inbuilt device location once unplugged. This is just how ios18 now functions. We cannot change that. It is not a GeoPort issue
