### ISSUE TITLE
my phone wont appear the windows geoport even though it has permissions and is connected through usb 

### ISSUE THREAD

**Issue by branden6u8** [davesc63/GeoPort#115]
- the connection list is empty and refreshing or connecting device does nothing 

it seems to work on similar apps but not this one, anyway to fix it?

windows 10 and ios 17.6.1

**Comment by branden6u8** [comment]
@davesc63

**Comment by davesc63** [comment]
Probably no iTunes installed

**Comment by branden6u8** [comment]
i fixed the connection issues but now i cant acutally simulate a location its fully connected but when cords are entered you cant simulate it am i doing something wrong? sorry if im missing something obvious here lol

**Comment by cohenerickson** [comment]
How did you fix the connection issue? I've got iTunes and all other iFakeLocation dependencies installed, iPhone asks for trust, yet no devices in list. IOS 18.1 iPhone XR
