### ISSUE TITLE
ios 18 nable to display connected devices

### ISSUE THREAD

**Issue by blueJYZ** [davesc63/GeoPort#117]
I also have the same problem, unable to display connected devices. I have already installed iTunes
win10 ios 18
Please help to see what the problem is，thanks
![3C793224-49A6-4a31-8E21-85858957A575](https://github.com/user-attachments/assets/7c9c3c72-df49-469d-ba0a-d2175ec7cdfc)

**Comment by cohenerickson** [comment]
Same issue here.

**Comment by Diomchen** [comment]
same

**Comment by davesc63** [comment]
On Windows, also ensure you have iTunes installed so that iOS devices can be discovered
