### ISSUE TITLE
Issue on Mac OS x86

### ISSUE THREAD

**Issue by rushivrox** [davesc63/GeoPort#12]
Getting the below error
<img width="576" alt="Screenshot 2024-04-04 at 11 30 56 PM" src="https://github.com/davesc63/GeoPort/assets/28400495/65c1fee6-10d4-4628-990f-8d96dc77ac3a">

**Comment by davesc63** [comment]
Fixing this. Platypus app is missing the admin flag
Didn’t capture this on the build machines as it worked the way I’ve currently built the app. Updating this and will advise once complete

**Comment by davesc63** [comment]
@rushivrox updated. Please redownload. The console should now be black background with blue writing so you'll know its new

**Comment by davesc63** [comment]
Closing as resolved
