### ISSUE TITLE
Mac IOS 14.7.1 ERROR

### ISSUE THREAD

**Issue by deathandtechno** [davesc63/GeoPort#123]
​/private/var/folders/rv/r8wgtq4d3zd972p0t0nbncdr0000gn/T/AppTranslocation/4E05E23C-F874-4F60-9C9F-98F177CEF046/d/GeoPort-mac.app/Contents/Resources/script: line 8: ./GeoPort: Bad CPU type in executable

what do?

**Comment by davesc63** [comment]
You're probably using the arm version on intel or vice versa
