### ISSUE TITLE
The frequency of update the location at replaying the GPX file.

### ISSUE THREAD

**Issue by D4box** [davesc63/GeoPort#124]
If the distance between points in a GPX file is too long, the track playback will be discontinuous. If the points are too close and dense, it may cause position updates to be blocked. Could you create a program to automatically adjust the point spacing to match the update frequency?

**Comment by D4box** [comment]
I conducted further tests, and it appears that the inability to send packets starts after a certain number of packets have been sent, rather than being caused by the frequency of sending.

**Comment by davesc63** [comment]
Yes, it is currently an overload on the service. Clearing the buffer also resets the spoofed location. Which some users do not like.

There is currently no good work around as yet

**Comment by D4box** [comment]
Could you please share the development environment for the project?
