### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by AliMickey** [davesc63/GeoPort#13]
Great work on this.

Any plans to release the source code?

**Comment by davesc63** [comment]
Thanks @AliMickey l!
I’m planning to release the code but so many changes have been worked on - that has been my focus. 

I also want to build a bit of a community around GeoPort first

**Comment by davesc63** [comment]
I also think people will be shocked at how crap the code is 😂

**Comment by AliMickey** [comment]
Good to know, I was planning on making something like this as well built off the original ifakelocation, so I'm eager to help once you are ready to release the code.
