### ISSUE TITLE
4.0有BUG吧

### ISSUE THREAD

**Issue by akinaedison** [davesc63/GeoPort#130]
根本打不开？

**Comment by davesc63** [comment]
?
Screen shot? What OS download?

**Comment by akinaedison** [comment]
![photo_2024-12-20_15-01-38](https://github.com/user-attachments/assets/bb6c00e8-b1f7-456e-8bda-f3d4c259d71a)
W11 64位

**Comment by davesc63** [comment]
Thank you... Fixing it now

**Comment by 12753kk** [comment]
![Uploading 5cd605beb498041043272a95b5cc857.png…]()

**Comment by 12753kk** [comment]
![5cd605beb498041043272a95b5cc857](https://github.com/user-attachments/assets/055d50ce-80f4-4e22-9c05-42275c830001)

**Comment by akinaedison** [comment]
![image](https://github.com/user-attachments/assets/65364858-407b-4734-a6fd-bae017555a92)

**Comment by davesc63** [comment]
please try this version of 4.0.1

**Comment by davesc63** [comment]
V4.0.2 is now latest
