### ISSUE TITLE
Version 4.0.1 still cannot work

### ISSUE THREAD

**Issue by Siason** [davesc63/GeoPort#131]
![屏幕截图 2024-12-20 165236](https://github.com/user-attachments/assets/10244cd3-0f86-4afd-85da-e9111d809814)

**Comment by Siason** [comment]
Under Windows11

**Comment by davesc63** [comment]
I hate pyinstaller so much. Working on Win11 as raw code, fails when compiled.
Working on it but reverted back to 3.0.0 as the main version for now

**Comment by davesc63** [comment]
Please try again on 4.0.1

**Comment by Siason** [comment]
Cool，it works

**Comment by davesc63** [comment]
Awesome. I hate pyinstaller!!

**Comment by Siason** [comment]
Hahaha, new situation.  Failed to connect to my iPad (iOS 17.5.1).
![屏幕截图 2024-12-20 194646](https://github.com/user-attachments/assets/78985f94-4c4b-40a0-97ed-f0d9bfb7c653)
