### ISSUE TITLE
GeoPort 4.0.1 - Issue

### ISSUE THREAD

**Issue by spagasaurus** [davesc63/GeoPort#132]
Unable to start GeoPort after installing the new 4.0.1 version. Running Mac OS X 15.1.1 on Apple Macbook Pro M1 Pro. Restarted after installing. Uninstalled and reinstalled - same issue as below.

2024-12-21 11:44:25,273 - INFO - Running as Sudo
2024-12-21 11:44:25,277 - INFO - Serving: http://localhost:60715
Traceback (most recent call last):
  File "main.py", line 1551, in <module>
  File "flask_socketio/__init__.py", line 650, in run
RuntimeError: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.
[PYI-86205:ERROR] Failed to execute script 'main' due to unhandled exception: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.
[PYI-86205:ERROR] Traceback:
Traceback (most recent call last):
  File "main.py", line 1551, in <module>
  File "flask_socketio/__init__.py", line 650, in run
    raise RuntimeError('The Werkzeug web server is not '
RuntimeError: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.

**Comment by davesc63** [comment]
Far out. Will fix in a few hours

**Comment by spagasaurus** [comment]
Haha i'm not having much luck with 3.0 and the 4.0.1 releases. All good mate, no rush! I've rolled back to v.2.3.3 again. Appreciate all your hard work and effort!

**Comment by davesc63** [comment]
Please test 4.0.2 if you get a chance. Windows works

**Comment by spagasaurus** [comment]
Works on Mac now - thanks!
