### ISSUE TITLE
"An existing connection was closed by the remote host" after using the tool for some time (Windows)

### ISSUE THREAD

**Issue by Noche9001** [davesc63/GeoPort#15]
I've been playing around with the tool for a few hours, what I noticed is that at some point, I cannot change the location anymore. I get the following error:
![Screenshot 2024-04-08 105331](https://github.com/davesc63/GeoPort/assets/64547700/9578e602-1c82-4fe7-8780-67bf503c91c6)

--> "An existing connection was closed by the remote host"

I was able to bypass the error by connecting my phone through a different USB-port, but I'm running out of them. Tried both restarting my pc and my phone. Reinstalling does not help either.

**Comment by GeneralLam** [comment]
Following this. No matter what I try I keep getting this exact error. Any help is appreciated.

**Comment by davesc63** [comment]
I'm honestly not working on this at the moment. I don't experience it myself on Windows and I am perfoming a lot of connections during development.

I also think this issue may go away once I update the code. The error probably comes from the windows driver we have to use, but from ios 17.4 we have another option available. I just haven't got to testing / implementing newer code.

For now - your best work around is probably removing the Windows drivers / UsbNcm adapters

**Comment by Noche9001** [comment]
A reliable way to bypass the error I found is disabling developer mode manually and then reactivating it through the tool.

**Comment by Noche9001** [comment]
A reliable way to bypass the error I found is disabling developer mode manually and then reactivating it through the tool. Let's hope it's fixed by the updated code!
