### ISSUE TITLE
Map is not working and Message: "{"error":"'NoneType' object has no attribute 'split'"}" showing

### ISSUE THREAD

**Issue by aiyoof** [davesc63/GeoPort#17]
![Screenshot 2024-04-12 074248](https://github.com/davesc63/GeoPort/assets/146498806/23f333bc-257e-4638-9af0-5686c2cbc755)
I had my location set to a different place but now I find out that it's not workign in the middle of the night and that it undid it self. I try to reset it to where I had it before but the app itself is none working either producing this error, and the map is not even showing.

**Comment by davesc63** [comment]
Thanks for reporting. This is a problem upstream from GeoPort. As we pull in javascript from CDN and maptiles from a map provider... these are all online and it appears at the moment that service is having intermittent issues.

I have seen up to 2 minutes for the map to load. Nothing we can do when it's coming from an internet delivered service

**Comment by aiyoof** [comment]
Was that the reason the location undid itself too? Thank you for your prompt response
