### ISSUE TITLE
Location Resets.

### ISSUE THREAD

**Issue by wjoaquin9** [davesc63/GeoPort#18]
Hi, I've been using it and after some minutes the location resets to its original point. Is there a way to make it stay locked even if I disconnect the device from the computer? Like, other apps I've used keep the location you simulate until you turn off your phone manually and turn it back on, then it resets.

**Comment by davesc63** [comment]
Your location does stay locked. So your experience is not the norm. 

More details on your device and pc. Perhaps send a copy of the server console when the location “resets”. Because there is no auto reset based on time. Location is reset only when you press disconnect or stop location
