### ISSUE TITLE
Unable to Create Device Tunnel Within 60 Seconds

### ISSUE THREAD

**Issue by blackcomb123** [davesc63/GeoPort#2]
I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3.
I am not able to connect

Dev Check result:  True
Developer Mode is true
passed dev mode check
entered ios17
Attempt 1: Error occurred - 
Attempt 2: Error occurred - 
Attempt 3: Error occurred - 
Attempt 4: Error occurred - 
Attempt 5: Error occurred - 
Attempt 6: Error occurred - 
Attempt 7: Error occurred - 
Attempt 8: Error occurred - 
Attempt 9: Error occurred - 
Attempt 10: Error occurred - 
Error: No devices found after multiple attempts
finally

**Comment by davesc63** [comment]
> I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3. I am not able to connect
> 
> Dev Check result: True Developer Mode is true passed dev mode check entered ios17 Attempt 1: Error occurred - Attempt 2: Error occurred - Attempt 3: Error occurred - Attempt 4: Error occurred - Attempt 5: Error occurred - Attempt 6: Error occurred - Attempt 7: Error occurred - Attempt 8: Error occurred - Attempt 9: Error occurred - Attempt 10: Error occurred - Error: No devices found after multiple attempts finally

This happens when you are not running as Admin/Sudo on Mac.
Did you get prompted for sudo password / touchID when launching the app?

Some troubleshooting options:
1. Run GeoPort by using `run.sh` 
2. if the above does not work you can try from terminal: `sudo ./GeoPort`

**Comment by davesc63** [comment]
> I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3. I am not able to connect
> 
> Dev Check result: True Developer Mode is true passed dev mode check entered ios17 Attempt 1: Error occurred - Attempt 2: Error occurred - Attempt 3: Error occurred - Attempt 4: Error occurred - Attempt 5: Error occurred - Attempt 6: Error occurred - Attempt 7: Error occurred - Attempt 8: Error occurred - Attempt 9: Error occurred - Attempt 10: Error occurred - Error: No devices found after multiple attempts finally

I downloaded the zip and tried it out. I had the same issue as admin.
I have rebuilt the package, tested, and working.
Please re-download the mac-arm bundle - https://github.com/davesc63/GeoPort/releases/download/v1.0.1/GeoPort-mac-arm-v1.0.1.zip

**Comment by khoo2009** [comment]
i cant see the my phone connect 
OS:Name	Microsoft Windows 11 Pro (v10.0.22621 Build 2262)
Itune : Version 12.12.10.1

---------------------------------------------------------------------------------------------------------------------------------------------
2024-03-15 17:57:07 Revision-PC pyi_splash[6372] INFO A connection to the splash screen was successfully established.
clear splash
 * Serving Flask app 'main'
 * Debug mode: on
2024-03-15 17:57:07 Revision-PC werkzeug[6372] INFO WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:54321
2024-03-15 17:57:07 Revision-PC werkzeug[6372] INFO Press CTRL+C to quit
test: []
2024-03-15 17:57:12 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:12] "GET / HTTP/1.1" 200 -
2024-03-15 17:57:12 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:12] "GET /api/fuel_types?region=All HTTP/1.1" 200 -
2024-03-15 17:57:13 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:13] "GET /api/data/?region=All HTTP/1.1" 404 -
dev list is:  []
[]
2024-03-15 17:57:13 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:13] "GET /list_devices HTTP/1.1" 200 -
2024-03-15 17:57:15 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:15] "POST /update_location HTTP/1.1" 200 -
dev list is:  []
[]
2024-03-15 17:57:18 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:18] "GET /list_devices HTTP/1.1" 200 -
dev list is:  []
[]
2024-03-15 17:57:41 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:57:41] "GET /list_devices HTTP/1.1" 200 -
dev list is:  []
[]
2024-03-15 17:58:00 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:58:00] "GET /list_devices HTTP/1.1" 200 -
data:  {'udid': ''}
2024-03-15 17:58:02 Revision-PC wintun[6372] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-03-15 17:58:02 Revision-PC wintun[6372] INFO WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.
2024-03-15 17:58:02 Revision-PC wintun[6372] INFO use existing WeTestUsbFilter driver.
2024-03-15 17:58:02 Revision-PC wintun[6372] INFO use existing WeTestUsbNcm driver.
Attempt 1: No devices found
Attempt 2: No devices found
Attempt 3: No devices found
Attempt 4: No devices found
Attempt 5: No devices found
Attempt 6: No devices found
Attempt 7: No devices found
Attempt 8: No devices found
Attempt 9: No devices found
Attempt 10: No devices found
Error: No devices found after multiple attempts

2024-03-15 17:58:53 Revision-PC werkzeug[6372] INFO 127.0.0.1 - - [15/Mar/2024 17:58:53] "POST /connect_device HTTP/1.1" 200 -

---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by davesc63** [comment]
> * dev list is:  []

You have a different issue. You probably don't have iTunes installed because no device is being detected via USB, or the Apple Mobile Device service is not listening on port 27015

You will need to ensure:

- iTunes is installed
- Apple Mobile Device Service is running
- Your machine is listening on port 27015 (in cmd run `netstat -an` and look for port 27015)

**Comment by davesc63** [comment]
> I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3. I am not able to connect
> 
> Dev Check result: True Developer Mode is true passed dev mode check entered ios17 Attempt 1: Error occurred - Attempt 2: Error occurred - Attempt 3: Error occurred - Attempt 4: Error occurred - Attempt 5: Error occurred - Attempt 6: Error occurred - Attempt 7: Error occurred - Attempt 8: Error occurred - Attempt 9: Error occurred - Attempt 10: Error occurred - Error: No devices found after multiple attempts finally

Ok, I've replicated this and I can't explain it. Here's the flow:

1. I created run.sh and GeoPort locally, then add to the zip file
2. Upload zip to github
3. Download zip from github
4. Open zip with "archive utlitiy" in the downloads folder
5. execute ./run.sh
6. **No device found timeout**
7. Here's what I can't explain - Move the two files (run.sh and GeoPort) out of the Downloads directory to any where else, ie /Users/yourname/test
8. execute `run.sh` and the app runs fine!

I can't explain it but something about the Downloads folder isn't allowing it to run. Even if I move my source build files from the output directory into a Downloads/Test directory it doesn't establish the tunnel!!

Would love an explanation here!

**Comment by blackcomb123** [comment]
> > I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3. I am not able to connect
> > Dev Check result: True Developer Mode is true passed dev mode check entered ios17 Attempt 1: Error occurred - Attempt 2: Error occurred - Attempt 3: Error occurred - Attempt 4: Error occurred - Attempt 5: Error occurred - Attempt 6: Error occurred - Attempt 7: Error occurred - Attempt 8: Error occurred - Attempt 9: Error occurred - Attempt 10: Error occurred - Error: No devices found after multiple attempts finally
> 
> I downloaded the zip and tried it out. I had the same issue as admin. I have rebuilt the package, tested, and working. Please re-download the mac-arm bundle - https://github.com/davesc63/GeoPort/releases/download/v1.0.1/GeoPort-mac-arm-v1.0.1.zip

Thank you for your prompt response, it is working fine now.

If possible can you set any notification once the fake location is set, it doesnt prompts anything once you click the button. I tried a few times and then thought let me go and check in the app on the phone. The location was changed.

Same thing when stopping it no notifcation.

Thank You and keep up the great work really appreciate.
Jeet

**Comment by davesc63** [comment]
> > > I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3. I am not able to connect
> > > Dev Check result: True Developer Mode is true passed dev mode check entered ios17 Attempt 1: Error occurred - Attempt 2: Error occurred - Attempt 3: Error occurred - Attempt 4: Error occurred - Attempt 5: Error occurred - Attempt 6: Error occurred - Attempt 7: Error occurred - Attempt 8: Error occurred - Attempt 9: Error occurred - Attempt 10: Error occurred - Error: No devices found after multiple attempts finally
> > 
> > 
> > I downloaded the zip and tried it out. I had the same issue as admin. I have rebuilt the package, tested, and working. Please re-download the mac-arm bundle - https://github.com/davesc63/GeoPort/releases/download/v1.0.1/GeoPort-mac-arm-v1.0.1.zip
> 
> Thank you for your prompt response, it is working fine now.
> 
> If possible can you set any notification once the fake location is set, it doesnt prompts anything once you click the button. I tried a few times and then thought let me go and check in the app on the phone. The location was changed.
> 
> Same thing when stopping it no notifcation.
> 
> Thank You and keep up the great work really appreciate. Blackcomb

Awesome mate! Love a good result!
I will take that feedback on board, I've had it twice now so it seems like its needed!

I had a suggestion to grey out the set location once its done, but my reasoning against that is that you can constantly change location as many times as you want - some apps / games you need to keep changing rather than set once

stay tuned for 1.0.2 and I'll add some notifications :)

**Comment by davesc63** [comment]
> > > I am connecting my iPhone 15 Pro Max running iOS 17.4 via Apple Macbook Air M3. I am not able to connect
> > > Dev Check result: True Developer Mode is true passed dev mode check entered ios17 Attempt 1: Error occurred - Attempt 2: Error occurred - Attempt 3: Error occurred - Attempt 4: Error occurred - Attempt 5: Error occurred - Attempt 6: Error occurred - Attempt 7: Error occurred - Attempt 8: Error occurred - Attempt 9: Error occurred - Attempt 10: Error occurred - Error: No devices found after multiple attempts finally
> > 
> > 
> > I downloaded the zip and tried it out. I had the same issue as admin. I have rebuilt the package, tested, and working. Please re-download the mac-arm bundle - https://github.com/davesc63/GeoPort/releases/download/v1.0.1/GeoPort-mac-arm-v1.0.1.zip
> 
> Thank you for your prompt response, it is working fine now.
> 
> If possible can you set any notification once the fake location is set, it doesnt prompts anything once you click the button. I tried a few times and then thought let me go and check in the app on the phone. The location was changed.
> 
> Same thing when stopping it no notifcation.
> 
> Thank You and keep up the great work really appreciate. Blackcomb

@blackcomb123 - How's this for a notification - 
<img width="549" alt="geoport-notification" src="https://github.com/davesc63/GeoPort/assets/66445532/2522ad78-c82a-48c0-837a-a329f273ca1d">

**Comment by blackcomb123** [comment]
This looks perfect thank you.

**Comment by davesc63** [comment]
Resolved. Feedback used to update app
