### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by DVDphobia** [davesc63/GeoPort#20]
![Screenshot from 2024-04-15 20-22-12](https://github.com/davesc63/GeoPort/assets/100691352/cf5a6369-5413-4925-a8df-ede99d22e856)
can anyone help me solve this error!

**Comment by davesc63** [comment]
Please show more of the log
This happens on windows if your Windows firewall settings are blocking the connection

See this: https://github.com/davesc63/GeoPort/blob/main/FAQ.md

**Comment by DVDphobia** [comment]
![Screenshot_2024-04-16_13-26-31](https://github.com/davesc63/GeoPort/assets/100691352/e20ddd3c-1478-4457-9ceb-feb46c62be81)
This is the full log of is and i am using Ubuntu 23.04

**Comment by davesc63** [comment]
@DVDphobia ahh Linux. Can you try running the binary as sudo. 

Sudo ./GeoPort

**Comment by davesc63** [comment]
Any update? @DVDphobia

**Comment by auswill2** [comment]
Please help. Using windows. 
I dont see any devices in the drop down list.  Have tried all the firewall things in faqs.
![Untitled](https://github.com/davesc63/GeoPort/assets/167939791/f899ee1c-5b1a-4388-9665-022135fa4967)

**Comment by DVDphobia** [comment]
Still don't know what the error related to. @davesc63

**Comment by davesc63** [comment]
> Still don't know what the error related to. @davesc63

I'm not sure I can help you sorry.
I gave you the command to try. Is it working now, or not? did you try the command I gave?

**Comment by davesc63** [comment]
> Please help. Using windows. I dont see any devices in the drop down list. Have tried all the firewall things in faqs. ![Untitled](https://private-user-images.githubusercontent.com/167939791/325031645-f899ee1c-5b1a-4388-9665-022135fa4967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzQ0OTEsIm5iZiI6MTcxMzkzNDE5MSwicGF0aCI6Ii8xNjc5Mzk3OTEvMzI1MDMxNjQ1LWY4OTllZTFjLTViMWEtNDM4OC05NjY1LTAyMjEzNWZhNDk2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNDQ5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWYwNWQ2ZDM5MWNiNTVmZmIzNTVmY2RmN2ExZTVlZmZkMTBkNTE0ODY0ODZmZmEyNTc1MWFjN2UzNDc0NjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.caBsqLDy0iv1gv4VKwhPhCSLgabJSS8TS7nFq023lHc)

This is odd and you should open an issue.
What is your ios device and version?

It seems to detect the device but hangs when we enable wifi connections... which is a simple on/off

If the attribute wasn't present, I would expect it to crash with an error. This seems like an issue with your iOS. Is an update available? can you restart your device?

**Comment by auswill2** [comment]
Thanks your reply but I just fixed the issue by installing iTunes.  Works great now thanks

**Comment by davesc63** [comment]
> Thanks your reply but I just fixed the issue by installing iTunes. Works great now thanks

I've just found the issue for this.
iTunes helps, but odd that you had the "raw" devices if iTunes wasn't installed.

The issue was/is due to no pair record found in c:\programdata\Apple\lockdown

Coincidence as I am fine-tuning the v2.2.0 and updating the way I search for pair records

**Comment by DVDphobia** [comment]
> > Still don't know what the error related to. @davesc63
> 
> 
> 
> I'm not sure I can help you sorry.
> 
> I gave you the command to try. Is it working now, or not? did you try the command I gave?

It might be causing by other problems maybe not cause by not using Sudo command and i already tried it.

**Comment by vocalvincent** [comment]
Not sure if this helps but I found that my GeoPort.exe was syncing with OneDrive in my Downloads/Documents/Desktop folders which wasn't showing the device list for some reason (Windows 11)
