### ISSUE TITLE
[Bug] OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by RL-William-Coates** [davesc63/GeoPort#21]
Towards the end of a testing session, I got the error `[Bug] OSError: [Errno 24] Too many open files` when I pressed the 'Stop Location' button. After this, the 'Simulate Location' button appeared to work, but was in fact not updating the location.

I'm on the latest version, on an ARM Mac.

[output.log](https://github.com/davesc63/GeoPort/files/15009176/output.log)

**Comment by davesc63** [comment]
I believe this was due to improper handling of thread termination. Have a resolution in v2.2.0 to properly close location threads when "Stop Location" is pressed
