### ISSUE TITLE
Walk Features/Ban Evasion

### ISSUE THREAD

**Issue by Scintilical** [davesc63/GeoPort#23]
Not sure how much is actually possible within developer mode, but PoGo can use elevation data to evaluate bans, adding a random +-small elevation to the current to make the software more ban evasive.

And programmable walk paths with a velocity?, implementation of this shouldn't be too difficult and would be a huge quality of life change <3

**Comment by davesc63** [comment]
I’ve got most of that built already for the next release

https://geoport.me/geoport-gpx-auto.mp4

**Comment by Scintilical** [comment]
I also can't get untethered working, are there any prerequisites for it working?

**Comment by davesc63** [comment]
What’s your iOS version and app version?

I introduced it in v 2.1 and it’ll work on ios16 and 17 devices. 

It get enabled by default after connecting with a USB cable to GeoPort the first time. 

If WiFi isn’t being discovered it’s probably related to your home network. Devices are discovered via bonjour / mDNS

**Comment by Scintilical** [comment]
The most updated iOS, I've been running it through cable and it keeps going into a state where the simulate location doesn't do anything, figured it's to do with my transfer cable. I'm on University Public WiFi so I assume that's causing the problem

**Comment by davesc63** [comment]
Yep they probably have a security device that is blocking it

**Comment by Scintilical** [comment]
Fair enough, do we have an ETA for the next patch?

**Comment by davesc63** [comment]
v2.2.0 is due in the next few days (time permitting)
