### ISSUE TITLE
Command Line Options

### ISSUE THREAD

**Issue by Mackamuir** [davesc63/GeoPort#25]
Would love a few command line options for this specifically on Linux, such as skipping opening web browser, set rsd data path, set serving port. Looking to run this in a container and unfortunately can't due to the browser requirement :(.

Also adding a cache to the web browser to save things like dark mode/fuel mode, type and location would be epic

**Comment by Mackamuir** [comment]
Basically just the ability to run the application in a LXC/docker container so it's always available on my network and would be able to access the application from my phone rather than have to use my computer, more of a convenience thing than anything else. Checked out foolspoof and it could work but I would rather use your pretty GUI ;)

**Comment by davesc63** [comment]
So after you raised this I thought “this is an epic idea and how I would use it” … except for a docker container. I’ll just run it an lxc or Ubuntu vm on proxmox. Then access the gui via browser on the lan. I can then spoof whenever

I love this idea and I’m using it this way right now

**Comment by davesc63** [comment]
@Mackamuir 
Adding these in, testing locally it's working fine.
The big test will be if pyinstaller accepts and works with them!

```python
parser.add_argument('--no-browser', action='store_true', help='Skip auto opening the browser')
parser.add_argument('--port', type=int, help='Specify port number to listen on for web browser requests')
```

I don't think there's any other arguments I need to accept

I'm looking at a config.ini (or similar) to save:

- last coordinates
- dark mode checked/not
- fuel mode checked/not

But those may get targeted for v2.4

**Comment by davesc63** [comment]
@Mackamuir 
v2.3 release
Command line switches added
