### ISSUE TITLE
Windows 10 PC | iPhone iOS 17.4.1

### ISSUE THREAD

**Issue by jjwekell** [davesc63/GeoPort#28]
![Geoport](https://github.com/davesc63/GeoPort/assets/63025820/04097206-7ca1-42c9-84ff-2fb33a36cb5b)
![image_123650291](https://github.com/davesc63/GeoPort/assets/63025820/c1df0071-b1f4-43dd-9e75-9e0853471afd)
![Capture](https://github.com/davesc63/GeoPort/assets/63025820/67c6dd06-2d7a-4726-b30b-2a67e7875556)

Knowns PC:
running as admin
not in download directory in C:/Test/
iTunes installed
windows defender private and public allowed
have turned off firewall entirely no luck, also followed steps exactly of enabling public private, then removing, and running geo as admin 

Knowns iOS:
developer mode enabled

Hardware:
Using USB-C to Lightning 

Wifi/USB:
Does not connect hangs during both

**Comment by davesc63** [comment]
@jjwekell  Can you remove GeoPort from you windows firewall completely so a new entry is created. 

Can you take a look at control panel - network connections and see if a pywintun adapter is being created

Can you try a WiFi connection. WiFi may appear to hang but it can take over 1 min sometimes (other times it’s a few seconds - working on what’s causing this for next release)

in this release and iOS version we don’t require a 3rd party “WeTest” driver

**Comment by jjwekell** [comment]
Firewall deleting and creating a new entry hasn't made it work

I am not seeing a pywintun adapter being created in my network view

Do I need py3 or another repository? Geoport isn't throwing any errors, it attempts to connect but, might not have what it needs to do so

Wifi stops attempting to connect after 10th attempt no luck making a connection

**Comment by davesc63** [comment]
@jjwekell i think this is an issue with pyinstaller and the driver hasn’t bundled properly

Worked on my test machine as a bundle but is already run the raw python code. I’ll take a look and update. 

To keep using GeoPort for now we will need to revert to the v2.1 release 

https://github.com/davesc63/GeoPort/releases/tag/v2.1

**Comment by jjwekell** [comment]
This is working for me now! Thank you for your hard work. 

2024-04-26 15:53:20 ASDF wintun[10820] INFO WeTestUsbFilter driver not exists or expired.
2024-04-26 15:53:20 ASDF wintun[10820] INFO Installing WeTestUsbFilter driver
2024-04-26 15:53:28 ASDF wintun[10820] INFO Install WeTestUsbFilter completely, exit: 3010
2024-04-26 15:53:28 ASDF wintun[10820] INFO WeTestUsbNcm driver not exists or expired.
2024-04-26 15:53:28 ASDF wintun[10820] INFO Installing win10_WeTestUsbNcm driver
2024-04-26 15:53:29 ASDF wintun[10820] INFO Install win10_WeTestUsbNcm completely, exit: 0

**Comment by davesc63** [comment]
If you now go back to v2.2 does it work?

id like to confirm if the pytun adapter gets created. In v2.2 there should no longer be the Wetest being used. 

I have a feeling there is something added by Wetest that helps us still even tho that driver isn’t being used. As my windows machine has always had it installed, it didn’t appear as an issue but a new, fresh windows seems to be missing something

**Comment by jjwekell** [comment]
I just did a fresh install of windows, I'll have a shot tomorrow to give it another go. Will update asap. Thank you for being so thorough.

**Comment by jjwekell** [comment]
I'm not able to get anywhere with it.

It's not grabbing either wetestusb driver

**Comment by jjwekell** [comment]
Got it working, kept trying to go through the steps. I am unsure what made it work very sorry to report. Reconnecting the USB connection, restarting & deleting the firewall rules, restarting Geoport, it finally asked on iOS if it was trusted at the right time in the rotation.

**Comment by davesc63** [comment]
Thanks for the reply!

**Comment by davesc63** [comment]
This is great feedback that a fresh install of windows doesn’t have the usb communication ability. 

The older version of GeoPort (v2.1) uses an older version of pymobiledevice which installs the WeTest driver, but we only use part of it being the UsbNcm. 

If v2.1 is used for the UsbNcm driver then you switch back to v2.2 it will run with a newer runner adapter

I’m trying to explain this to the pmd3 dev
