### ISSUE TITLE
Stuck on "Getting location information now"

### ISSUE THREAD

**Issue by mattabtchrist** [davesc63/GeoPort#29]
![msg27181560-683367](https://github.com/davesc63/GeoPort/assets/168261832/31f42356-4ab5-42ad-b199-8cdcd3283f9f)
Hi there, thanks for supporting the community with this project. How do I get around this in Monster Hunter Now? Because of it, no monsters will load even though the location simulation works.

**Comment by davesc63** [comment]
I’m unfamiliar with this app. Let me take a look and see. Unsure what they are checking if your gps location is spoofed
