### ISSUE TITLE
v1.01 on x86 mac cannot execute binary file

### ISSUE THREAD

**Issue by IceSt0rm** [davesc63/GeoPort#3]
running mac os sonoma even after moving it from downloads directory. still getting the same error cannot execute binary file

**Comment by IceSt0rm** [comment]
note to add that the previous version works perfectly

**Comment by davesc63** [comment]
Can you confirm your operating system details?

are you trying to run the Mac x86 version on a M1 / M2 Mac? Because that’s the error message you get

**Comment by IceSt0rm** [comment]
macbook air 2017 intel i5 , mac os sonoma 14.3.  im running the correct build

**Comment by davesc63** [comment]
I’ll look at this today and rebuild the binary. I have v1.0.2 updates being added in so new binaries requiredSent from my iPhoneOn 16 Mar 2024, at 7:30 am, IceSt0rm ***@***.***> wrote:﻿
macbook air 2017 intel i5 , mac os sonoma 14.3.  im running the correct build

**Comment by davesc63** [comment]
v1.0.2 is now released. 
x86 - Intel Mac version also recompiled
