### ISSUE TITLE
V2.2.0?

### ISSUE THREAD

**Issue by Scintilical** [davesc63/GeoPort#31]
The website says 2.2.0 but the new download still gives v2.1.0 is there somewhere we can download the new version? Thank you in advance <3

**Comment by davesc63** [comment]
@Scintilical v2.2 is in the github releases area, but I've "hidden" it from the main download pages.
There were some reported issues on Windows, so I thought it'd be best to hide it for now while I add some tweaks

**Comment by davesc63** [comment]
@Scintilical v2.3 released
