### ISSUE TITLE
Feature request - Set proxy settings

### ISSUE THREAD

**Issue by kenny12341** [davesc63/GeoPort#32]
Add ability to set proxy settings

Currently unable to launch on work devices due to corp proxies

<img width="572" alt="image" src="https://github.com/davesc63/GeoPort/assets/88468843/ff1fdc46-2623-45f8-b516-e460c22fe711">

**Comment by davesc63** [comment]
@kenny12341 0 will you be using "Fuel Mode" or just location spoofing
I can bypass this by handling the exception. This is specific to fuel mode, but as you experience, the crash halts the entire app

I also can't accept user input in that window. So an option may be to use a config file

**Comment by kenny12341** [comment]
Oh thanks for getting back! I was planning to use just for fuel mode so would be amazing to bypass this error

**Comment by davesc63** [comment]
@kenny12341 

Done, have added this code. Will be creating v2.3 soon. Stay tuned

`    except NameResolutionError as e:
        logger.error("Error: Name resolution failed.")
        logger.error(f"API is unreachable or there was an error during the request")
        logger.error("Sorry - Fuel data is not available")
        logger.error(f"Details: {e}")
        return None`

**Comment by kenny12341** [comment]
> @kenny12341
> 
> Done, have added this code. Will be creating v2.3 soon. Stay tuned
> 
> ```python
>     except NameResolutionError as e:
>         logger.error("Error: Name resolution failed.")
>         logger.error(f"API is unreachable or there was an error during the request")
>         logger.error("Sorry - Fuel data is not available")
>         logger.error(f"Details: {e}")
>         return None```
> ```

Legend thank you!

**Comment by davesc63** [comment]
@kenny12341 v2.3 released with the handling of name resolution
