### ISSUE TITLE
Way to go to location.

### ISSUE THREAD

**Issue by xXWapixelXx** [davesc63/GeoPort#33]
Hey is it possible to like input a location and then make it walk to it or cycle or maybe even say to like showing you went using your car? because for alot of tracking apps they will just show a straight line tp to the other side. and that could be the obv giveaway. is it also possible to make it hosted online? so like Changing the location not only on localhost.

**Comment by davesc63** [comment]
@xXWapixelXx 

Thanks for the feedback.
Check out v2.2 / v2.3 where I have introduced the ability to replay a track file or to create your own by drawing on the map.
There is currently no option to type a destination and create a route - and im not currently planning on it. But votes and donations can help prioritize.

GeoPort cannot be hosted online yet. Since we require access to your iOS device via USB or local wifi. Both of which cannot be achieved when hosted.

However, locally, you could host GeoPort on a laptop/PC. Then:

- Take note of your machines IP that is running GeoPort
- On your phone open a browser
- Browse to http://<ip of your machine>:<port> example `http://192.168.1.20:54321`
- This will load GeoPort in your phones browser and you can then control your iOS device via Wifi

If anyone else reads this. I am attempting WebUSB and then I can offer GeoPort "as a service" hosted on the web. But WebUSB doesn't seem to have a lot of developers or experience

**Comment by xXWapixelXx** [comment]
hey when i make it use routes its using car routes, is there anyway making it use walking routes for when u click walking?

**Comment by davesc63** [comment]
this is possible, I will need to look into it and the free services that provide this capability

**Comment by davesc63** [comment]
Ok it's possible and I've made it work.
Just need to refine it so it can be a bit more user friendly rather than hardcoded.

The current issue is the routing backend (not in my control) is hardcoded to driving and it ignores any request for foot or bicycle profiles

**Comment by xXWapixelXx** [comment]
alright thanks, I've got a second question do you know why some apps dont see me like move location? I've tested few apps and they worked but when i used Find my kids app it basically just stated that i was chilling at home while snapchat and find my said i was in the USA

**Comment by davesc63** [comment]
We are setting a whole of device GPS spoof. Some apps may also try to look at other data points, like your IP address to determine where you are.

That's where you might need a VPN so your device IP will also appear in the location

**Comment by xXWapixelXx** [comment]
so basically when i use a vpn it should work?

**Comment by xXWapixelXx** [comment]
oh yeah, i see now that i also uses motion and fitness to accurate see your location do u perchance know any way to like also bypass that?

**Comment by xXWapixelXx** [comment]
Basically from what I’ve seen now is motion and fitness and your GPS.

**Comment by davesc63** [comment]
@xXWapixelXx v2.3.1 released, walking is now the default (and only) routing method

**Comment by xXWapixelXx** [comment]
oh yeah btw bro let me donate for your hard work, thanks for everything.

**Comment by FLECeRx** [comment]
Hello, my friend. I want to know about your location spoofing app. I think that this definitely works for you, as a developer.

I want to ask you. Could you check the performance of your application on the game ingress prime? Does substitution work in this game, does the route work?

If you can show that it works, I will definitely pay you money. Thanks for your help.

**Comment by davesc63** [comment]
> Hey, I got a little question. Is there also a way to add best routes to it? For example Google maps when u put ur coordinates in then Google maps would like give me the option for car, walking and or using public transportation or cycling. I would also like to see if public transportation would be possible. So then it would walk to the nearest bus stop or tram stop and then just follow the tram lines and then stop at the other stop and then you’ll basically walk the rest.

I’ll look into this one. Can you tell me more about how this would be helpful and how you will use it?

it would need a more advanced routing provider and some work. So I’m trying to gauge the benefit vs time

**Comment by davesc63** [comment]
> work?

I don’t understand you comment sorry. 
the release notes have plenty of demos showing the app working

**Comment by xXWapixelXx** [comment]
> > Hey, I got a little question. Is there also a way to add best routes to it? For example Google maps when u put ur coordinates in then Google maps would like give me the option for car, walking and or using public transportation or cycling. I would also like to see if public transportation would be possible. So then it would walk to the nearest bus stop or tram stop and then just follow the tram lines and then stop at the other stop and then you’ll basically walk the rest.
> 
> I’ll look into this one. Can you tell me more about how this would be helpful and how you will use it?
> 
> it would need a more advanced routing provider and some work. So I’m trying to gauge the benefit vs time

Basically for apps that keep track of your routes that you’ve taken. They can always track back and if the dev sees me flying across the world that would be a problem 😭 so it should look legit. Also how long does the location stay on my phone if I just unplugged my phone? Can I just set my location and just unplug my phone and then the location would be the same for the next 10 hours?

**Comment by davesc63** [comment]
You can set your location, disconnect your device and walk away. It will remain in the last location indefinitely.
You then just reconnect to GeoPort and hit "Stop Location" to reset back to your real location.... or spoof again!

**Comment by xXWapixelXx** [comment]
Ah alright thanks, yesterday when I disconnected my phone it later one randomly resetted my location to ky real GPS after an hour. I still don’t know why or how since I was no where near my pc and was outside. But did further testing today and it didn’t occurred again. Still wondering how it randomly stopped tho.

**Comment by davesc63** [comment]
I've had the opposite. Forget to stop location, then while away from home try to use an app with location services (uber, takeaway) and location is somewhere else in the world

**Comment by xXWapixelXx** [comment]
😂😂

**Comment by FLECeRx** [comment]
> > work?
> 
> I don’t understand you comment sorry. the release notes have plenty of demos showing the app working

Did I understand correctly that you left this comment for me?
