### ISSUE TITLE
Console is stuck loading

### ISSUE THREAD

**Issue by BigBilti** [davesc63/GeoPort#34]
Im connecting a x86 Mac to IOS 17.4.1 via USB, and the console is stuck "loading" with this information (never loads in the URL by itself):

​2024-04-30 12:22:30 Noahs-MacBook-Pro-2.local GeoPort[5955] INFO 
Running as Sudo
2024-04-30 12:22:30 Noahs-MacBook-Pro-2.local GeoPort[5955] INFO 
Serving: http://localhost:64102
 * Serving Flask app 'main'
 * Debug mode: off

If I paste the provided URL in my browser, I get the location changer, but the map does not load in.

I was able to get it to work the first time I used the app. Thanks!

**Comment by davesc63** [comment]
@BigBilti What version are you running?
I am unable to reproduce on v2.3.2

I added cli arguments that if `--no-browser` is passed while executing GeoPort, the above is expected behavor (no browser auto-launch)
