### ISSUE TITLE
Route-Walking

### ISSUE THREAD

**Issue by Scintilical** [davesc63/GeoPort#37]
Nothing relating to the route-walk function seems to be working, the autoplacing of routes makes it incredibly difficult to route to where you actually want to go as it only uses pathways, and wont follow roads, seems to randomly place starting locations for routes at places at times miles away from the first selected location. Cannot load GPX files into the app, and cannot run the routes I set myself.

**Comment by Scintilical** [comment]
Building further upon this, for point one, it seems that the route walking jumps between the points you select and as a result the path shown does not determine the actual path of travel. 

The buttons on the left do not prevent a marker from being placed, which means you can accidentally ruin a route by pressing one of them. Preventing this from happening and adding an undo button would improve the user experience greatly.

It seems GPX files don't load properly, however Geojson files do. This is a promising update, if I wasn't a broke Uni student I would definitely be considering donating to you <3

**Comment by davesc63** [comment]
GPX loads fine. 
if you want a fuller experience I’d recommend using gpx studio to build your route and replay them in GeoPort - for now

when creating your route, small clicks are optimal. When you enable drawing mode the icon changes from the route to a pen and the cursor becomes a crosshair

undo was becoming a pain to implement but I will add it to the list. 

As you are a poor student who can’t donate, I provide this for free in my spare time. Donations help keep me motivated and prioritize new features :)
