### ISSUE TITLE
Route Walking Getting Stuck

### ISSUE THREAD

**Issue by Scintilical** [davesc63/GeoPort#38]
As a route is walking it will suddenly stop updating the location and will lock it to that place.
It prevents you from stopping the location, and disconnecting does not work, it requires a full device reset to fix, iOS 17.4

**Comment by davesc63** [comment]
The stop button will clear old threads on v2.3.2 and above- which clears the buffer that’s been overloaded

there is a delicate balance to be found to enhance this. The only way to keep spoofing is to clear the old locations. But doing this momentarily resets your location to your true location.
