### ISSUE TITLE
Feature Request - Importing Latitude and Longitude via JSON and Customizable Speed

### ISSUE THREAD

**Issue by MTDickens** [davesc63/GeoPort#47]
Hi there,
I'd like to propose a new feature: the ability to use JSON for importing latitude and longitude information, coupled with a customizable speed setting.

In essence, the feature would calculate the distance between two coordinates, then determine the travel time based on the set speed.

This could be very helpful for my fellow university students who are forced to track running tasks instead of doing whatever sport we like.

If implemented, I'd be more than happy to promote your software on the Telegram channel of my university.

**Comment by MTDickens** [comment]
BTW, in github there's been lots of "fake run"s for iOS <= 16 already, but not that much for iOS17. And most of them don't work for me.

**Comment by davesc63** [comment]
This feature is already in v2.3.3

You can create a gpx track and replay it at various speeds
