### ISSUE TITLE
Feature request. Repeat path

### ISSUE THREAD

**Issue by jordanjamesuk** [davesc63/GeoPort#52]
I love the tool so far. I often upload a path I've made and leave it running. It would be great if at the end of a path, instead of it stopping, it could just start again.

It's a small quality of life thing, so I'm happy to implement it myself when you release the source code (if you still plan on doing that soon).

While I'm putting this request in, I'd also like to ask about the location buffer not being auto reset. I read that you chose not to as it reset the location for a second and some users might not want that. Would you be able to make this a toggle-able option?

Cheers

**Comment by davesc63** [comment]
Considering this option
