### ISSUE TITLE
"error":"[Errno 11001] getaddrinfo failed"}

### ISSUE THREAD

**Issue by denizgint** [davesc63/GeoPort#53]
I get these error while disconnecting, stopping location. It does connect but when i click on change location, it does not change in Iphone.

**Comment by davesc63** [comment]
As I keep saying in these issues. You have overloaded your device with spoofing sessions.
The workaround is to "Stop Location" which terminates previous spoofs for the current session. If you physically disconnect your device during a session - I can't help you, you need to reboot your device.

I have a coded way currently that can auto-flush prior connections, but in testing people complained about a very slight reset to existing location.
