### ISSUE TITLE
Device Not Connecting

### ISSUE THREAD

**Issue by jakevert** [davesc63/GeoPort#54]
hello, i used the software roughly 2 days ago and worked flawlessly however, when i tried today. my iphone 14 (IOS 17.4) would not show on the device list. any help that anyone can offer would be greatly appreciated!

**Comment by jjwekell** [comment]
itunes update on PC?
- if so try running the app til it loads completely
iOS update to 17.5.1
- update from 17.4
update geoport.me version
-https://github.com/davesc63/GeoPort/releases/tag/v2.3.3

**Comment by davesc63** [comment]
What’s your computer you are connecting to?
If it worked flawlessly then no reason for it to no longer detect the device. Need more details
