### ISSUE TITLE
Never been able to run full Routes. Always stops somewhere before it reaches the end.

### ISSUE THREAD

**Issue by ItsMeKevi** [davesc63/GeoPort#57]
Tried it with different .geojson or .json files but its always the same issue. Mostly it just stops halfway through and then the whole application stops working until I restart. Using with IOS 17.5.1 both on Wifi and through usb. 

[GeoPortError.txt](https://github.com/davesc63/GeoPort/files/15456095/GeoPortError.txt)

**Comment by davesc63** [comment]
You’re flooding and overloading the spoofing service. Work around is to “stop location” after about 30 location spoofs to clear old connections
