### ISSUE TITLE
Connection Timeout : Unable to create device tunnel

### ISSUE THREAD

**Issue by rushivrox** [davesc63/GeoPort#6]
I am getting the below error upon trying to connect

<img width="506" alt="Screenshot 2024-03-30 at 8 00 46 AM" src="https://github.com/davesc63/GeoPort/assets/28400495/5803fc64-4fcf-4360-aa9e-5324abdef34e">

**Comment by davesc63** [comment]
Can you not upgrade to MacOS Sonoma?

**Comment by rushivrox** [comment]
Does it only work on MacOS Sonoma?

**Comment by rushivrox** [comment]
> Can you not upgrade to MacOS Sonoma?

Thanks, shall try
