### ISSUE TITLE
Location not revert after teleporting on ipad

### ISSUE THREAD

**Issue by hhojjn1** [davesc63/GeoPort#60]
if you check on your ipad in maps after you stop location - it doesnt revert back (wifi only ipad), it seems to be hit and miss with the stopping location and the ipad actually clearing the location

**Comment by davesc63** [comment]
Not a GeoPort issue. 
Happens on both WiFi and gps enabled devices. 

When you stop location sometimes it instantly goes back to original. Other times it can take a few minutes. In maps you will notice your location marker goes grey rather than blue
