### ISSUE TITLE
Downloading device software tencent

### ISSUE THREAD

**Issue by mehers30** [davesc63/GeoPort#61]
Hi, 
Just wondering about the downloading of device software Tencent WeTrust USB by Tencent Technology.
Is this safe to install especially being from a Chinese company.

**Comment by davesc63** [comment]
Your choice. 
The alternative spoofing apps are all Chinese made and owned

To avoid using the third party driver on windows, update to iOS 17.4+

Uses a native connection method and is much much faster than the WeTest driver method

**Comment by mehers30** [comment]
Hi, Im currently running iOS 17.4.1 but it is still asking me to download the WeTest driver. How can I bypass this?
