### ISSUE TITLE
Pokemon Go Error 12 Failed to Detect Location

### ISSUE THREAD

**Issue by rawa29** [davesc63/GeoPort#63]
This application along with many other spoofing apps are getting this error when playing Pokemon Go. There's probably been some changes in spoofing detection on Niantics side. I'm not sure if this qualifies as an "Issue" but I'm giving it a shot.

I'm sure you're aware of the issue and I hope it can be fixed. Thanks!

![IMG_FCDB56689804-1](https://github.com/davesc63/GeoPort/assets/3874378/81f87354-30df-4561-aada-b65f7aafeb03)

**Comment by psychodusk** [comment]
Same here, likely has to do with Niantic switching up things. A big bummer, because this method was very easy to use, very **safe**, and very iOS friendly. I really hope it'll work again soon, as this month is truly a good month to spoof. Definitely don't want to miss out on Landorus, Ho-Oh, Yveltal, Shadow Raikou, and Rayquaza.

**Comment by ck617** [comment]
Hope have good news soon.

**Comment by ElCapitano921** [comment]
I think this program is done for Pogo. The developer hasn't addressed the issue at all.

**Comment by psychodusk** [comment]
> I think this program is done for Pogo. The developer hasn't addressed the issue at all.

I think so too. It's a bummer, because I had high hopes with GeoPort. Easy to use, very safe, iOS friendly. And perhaps most importantly, it was advertised as "this app is free, and will always be". Oh well, it was fun while it lasted.

**Comment by davesc63** [comment]
Not related to GeoPort. Issue with all spoofers and PoGo

But people like @psychodusk who complain and demand a fix but don’t donate are the issue if you want a fix
