### ISSUE TITLE
Unable to 'Stop Location' iOS 17.5.1

### ISSUE THREAD

**Issue by aaronlam13** [davesc63/GeoPort#67]
Love the app guys! I was able to use GeoPort and Fuel Mode on an iPad running 16.6.1 to 'Simulate Location' and 'Stop Location'.

I've tried to do the same on a 2024 iPad Pro M4 running 17.5.1. I'm able to 'Simulate Location' successfully but unable to 'Stop Location' despite Geoport showing 'Location Cleared Succesfully'. I used Google Maps to check. No issues with same iOS on iPhone 15 Pro. 

Any ideas?

**Comment by neilaja** [comment]
Had the same issue today.  17.5.1, iPhone 12 Pro Max.
