### ISSUE TITLE
Does this work again or is error code (12) still a problem?

### ISSUE THREAD

**Issue by ItsMeKevi** [davesc63/GeoPort#70]
^^^^^^

**Comment by psychodusk** [comment]
Error code (12) is still a problem and the developer hasn't addressed this at all. Rip GeoPort.

**Comment by davesc63** [comment]
> Error code (12) is still a problem and the developer hasn't addressed this at all. Rip GeoPort.

What’s your udid. I can fix this

**Comment by MHV313** [comment]
> > Error code (12) is still a problem and the developer hasn't addressed this at all. Rip GeoPort.
> 
> What’s your udid. I can fix this

can you help me fix this if possible ? I'm using  iPhone 14 Pro Max iOS 17.5.1 on MacOS sonoma 14.5

**Comment by davesc63** [comment]
I haven’t tried to fix and it’s more than likely not possible for software spoofers
