### ISSUE TITLE
Unable to set location or clear location using wifi connection

### ISSUE THREAD

**Issue by chineseneo** [davesc63/GeoPort#71]
Seeing this error on the console: `ERROR Error setting location: [Errno 65] No route to host`.
Working fine using usb cable connection

**Comment by davesc63** [comment]
Stop GeoPort. Restart. No route to host is either you’ve disconnected the device and GeoPort is using old connection info or if you haven’t got that far it may be a driver issue. Send logsOn 27 Jun 2024, at 11:31 AM, Longkai Cao ***@***.***> wrote:﻿
Seeing this error on the console: ERROR Error setting location: [Errno 65] No route to host

**Comment by chineseneo** [comment]
Restarting GeoPort worked, thanks very much!
