### ISSUE TITLE
Link to local webpage not working as server is hosted on 0.0.0.0 rather than on localhost=127.0.0.1 on MacOS

### ISSUE THREAD

**Issue by Arcticfusion** [davesc63/GeoPort#75]
Every time I run GeoPort-mac (Version 2.1.0), the address that automatically opens cannot find a webpage. After some trial and error, I discovered I could find the webpage if I went to `0.0.0.0` instead of `localhost` and used the same assigned port.

Servers hosted using `0.0.0.0` can be viewed by other devices that know your device's IP address ([source](https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost)). I assuming this is not the intended behaviour.

My guess is some default value has changed. I am not sure if it would be for python or MacOS.

I'm running MacOS Sonoma 14.4.1 (23E224) on an M1 Macbook Pro and below is info on my python installations.
```bash
##  Versions for each python installation  ##
/opt/homebrew/Caskroom/miniconda/base/bin/python3 --version
# Python 3.12.2
/opt/homebrew/Caskroom/miniconda/base/bin/python --version
# Python 3.12.2
/opt/homebrew/bin/python3 --version
# Python 3.12.4
/usr/bin/python3 --version
# Python 3.9.6

##  Python Executables  ##
which python
# /opt/homebrew/Caskroom/miniconda/base/bin/python
sudo which python
# /opt/homebrew/Caskroom/miniconda/base/bin/python
which python3
# /opt/homebrew/Caskroom/miniconda/base/bin/python3
sudo which python3
# /opt/homebrew/Caskroom/miniconda/base/bin/python3
```

And here are some pics of the issue.

<img width="1089" alt="Screenshot 2024-07-03 at 3 39 57 PM" src="https://github.com/davesc63/GeoPort/assets/22851322/e41f98d3-b8fe-4883-b41b-41e509a42572" title="GeoPort console output while server is running">
<img width="596" alt="Screenshot 2024-07-03 at 2 53 49 PM" src="https://github.com/davesc63/GeoPort/assets/22851322/6a53d287-5f53-48f9-9658-e668905e9af6" title="localhost address that opens automatically has no webpage">
<img width="714" alt="Screenshot 2024-07-03 at 2 47 27 PM" src="https://github.com/davesc63/GeoPort/assets/22851322/344dcc4f-d9a4-4408-bd08-3ccb5685d4a1" title="0.0.0.0 address serves the GeoPort webpage">

**Comment by Arcticfusion** [comment]
Also, this authentication issue with the map may be related. I didn't want to make another whole issue for this if it was just because it was hosted on 0.0.0.0.

<img width="1185" alt="Screenshot 2024-07-03 at 3 42 56 PM" src="https://github.com/davesc63/GeoPort/assets/22851322/7cd545cc-2fa5-4d5d-a70c-278c7057b310" title="Page showing a repeating 401 Error Invalid Authentication message instead of the map">

**Comment by davesc63** [comment]
binding to 0.0.0.0 is by design which means "all interfaces"

if your machine doesn't understand "localhost" then you've got another issue

**Comment by Arcticfusion** [comment]
I can ping and start my own servers on `localhost` which does resolve to `127.0.0.1`.

Not sure why this app isn't working. I'm just using `fuel-spoof.sh` at the moment to avoid this issue.

But if you think this issue is not on your end, I guess I'll hit up stackoverflow with a new question. I'd been looking up this issue off and on for over a week.

**Comment by davesc63** [comment]
Sorry mate - its something local to you.
Just fired it up here. The map is working and my localhost works.
You should also be able to browse to your machines LAN IP address

But localhost not responding, something locally must not be happy
