### ISSUE TITLE
Driver not being auto installed

### ISSUE THREAD

**Issue by JTokyo** [davesc63/GeoPort#77]
![Screenshot 2024-07-14 120320](https://github.com/user-attachments/assets/15abb85a-cdc0-4cd7-88e0-9ccf61fb960d)

Says a driver needs to be installed but the program won't install it for some reason. Could I get the manual install instead?

**Comment by Swagout** [comment]
Same issue, i'm on 17.3.1 at the moment. Can't seem to get the app to work. 
![image](https://github.com/user-attachments/assets/ab77f0f8-0325-46ab-8a6d-bc0980e6257c)

**Comment by davesc63** [comment]
quite simply, its time for you to upgrade to 17.4 and beyond.
As the warning message says... they are upstream drivers that may stop being available at any time.

Sorry - out of our control
