### ISSUE TITLE
Error:  Failed to retrieve country name using locale. Using IP geolocation service

### ISSUE THREAD

**Issue by 1knth** [davesc63/GeoPort#79]
When zoomed in on the map, no streets or cities load. Only countries and continents. This is happening even after all public and private networks were allowed.
![image](https://github.com/user-attachments/assets/2cc038d6-e39f-4cee-b2cc-663d6efa2fd7)

**Comment by davesc63** [comment]
Was a temporary issue with the external map service provider, not GeoPort itself
