### ISSUE TITLE
Ios 17.3

### ISSUE THREAD

**Issue by saihaaaan** [davesc63/GeoPort#80]
bro your app works it open ups, but i'm facing issue when I try to connect my device with the USB, it saying error connecting and it says why on iOS 17.3 upgrade it to 17.4 so is it necessary to upgrade it to 17.4 or there are some bugs in you. I am using currently geo port Windows 2.3.3.

**Comment by saihaaaan** [comment]
is it compulsory to upgrade iOS 17.4?
Currently I am using iPhone 12

Are there any kind of extra drivers you need to install in your windows to work Geo port 2.3.3 ??

**Comment by saihaaaan** [comment]
![image](https://github.com/user-attachments/assets/5cdc264f-79df-40b0-bd03-3263cdf70c13)

**Comment by saihaaaan** [comment]
it's just loading error connecting and no further movement

**Comment by davesc63** [comment]
Yes because the upstream driver is probably no longer available from the 3rd party. 

Just upgrade because it’s a much better code and method of connecting and we don’t need the 3rd party driver to connect

**Comment by saihaaaan** [comment]
so, after upgrading iOS, 17.4, will it work completely fine???

**Comment by saihaaaan** [comment]
The next update I am having is 17.5.1.
Is it fine if I upgraded to 17.5.1 will it work??

**Comment by davesc63** [comment]
Yes
