### ISSUE TITLE
Unable to find any devices via GeoPort

### ISSUE THREAD

**Issue by AndersCF** [davesc63/GeoPort#82]
Hi there. I am on a Windows PC and GeoPort seems unable to find any USB devices in its device list. What am I missing? I simly allowed the .exe to do its magic and open in the browser. Allowed it to run as admin as requested and everything.

**Comment by AndersCF** [comment]
PS: I have tried to connect to an iPhone 11 with iOS 17.5.1, an iPhone 7 and a Samsung Galaxy S21 FE.

**Comment by davesc63** [comment]
Only iOS devices support. So don’t bother with the Samsung

You don’t see the device because you don’t have iTunes installed. Install it as it installs a prerequisite which allows the iOS device to be discoverable
