### ISSUE TITLE
ERROR Error setting location: InvalidService

### ISSUE THREAD

**Issue by MrLuke1110** [davesc63/GeoPort#83]
![image](https://github.com/user-attachments/assets/e2b8a3ad-4873-4f55-98cb-26c22e77d7e0)

**Comment by avall** [comment]
me too

**Comment by Mewinneryay** [comment]
i started getting this error too, did you find a fix?

**Comment by davesc63** [comment]
This is usually due to the connection no longer being valid to the device. Ie... you need to disconnect and reconnect.
Improved in v3.1 and beyond
