### ISSUE TITLE
Errno 11001

### ISSUE THREAD

**Issue by TaggDota** [davesc63/GeoPort#85]
Hi Dave,

Edge browser with url: localhost:54321.

i have successfully connect my device (ios 17.5.1) and set the proposed location, but when i click on the simulation button, the backend window reports as below:

2024-08-13 14:30:19 DESKTOP-XXXXXXX GeoPort[26336] ERROR Error setting location: [Errno 11001] getaddrinfo failed

could you help to check if there's a way to fix this?

**Comment by davesc63** [comment]
This would be due to disconnecting at some point. 

Restart the app to create a new connection table. 

I’ll remove connection table caching in the next version
