### ISSUE TITLE
Linux ARM Builds? Source code?

### ISSUE THREAD

**Issue by ghl3m0n** [davesc63/GeoPort#87]
I saw that the owner said that he will release the source code 5 months ago.. Where can I find it?
I really need to to build a ARM version for Linux to use it on my raspberry pi.
Thanks!

**Comment by davesc63** [comment]
It’s not that simple. 
Sure it can compile, but your rasperberry pi will also need usbmuxd compiled and supporting of pymobiledevice3. 

Personally, I’ve tried usbmuxd2 with limited success
