### ISSUE TITLE
Device not appearing from Select Device menu

### ISSUE THREAD

**Issue by debonair99** [davesc63/GeoPort#89]
Greetings,
I have tried multiple computers as well as restarting them and my iPhone but it's not appearing in the drop down menu under Select Device. A few weeks ago I ran it and was working perfectly
Using iOS 17.6.1 and a Windows 11 PC.
What could be the issue?
Cheers
![image](https://github.com/user-attachments/assets/3565b09c-8cbc-4f7e-ad45-c9580552f114)

**Comment by davesc63** [comment]
On Windows you probably don't have iTunes installed.
That installs the "Apple Mobile Device Service" - which is really usbmuxd that will listen on port 27015. Once you have that installed, GeoPort will work :)

**Comment by debonair99** [comment]
Legend, much obliged!
Back in business
