### ISSUE TITLE
Support for iOS 18?

### ISSUE THREAD

**Issue by Willxup** [davesc63/GeoPort#93]
I wanted to inquire whether the project is planned to support iOS 18 in the future.  As an avid user of your work, I am eager to know if there are any updates or plans regarding compatibility with the latest iOS version.

Thank you for your hard work and dedication to this project.

**Comment by davesc63** [comment]
Ios18 is supported and there’s been quite a bit of use during the ios18 beta :)

**Comment by screamloud** [comment]
Hey davesc,

As you mentioned that iOS 18 is supported, would you please update the main page to reflect this information, so that people stop asking the same question? :-)
