### ISSUE TITLE
IOS 18 Support?

### ISSUE THREAD

**Issue by ajaiupadhyaya** [davesc63/GeoPort#94]
Are there plans to allow Geoport for IOS18?

**Comment by davesc63** [comment]
It’s supported and working for >100 users. What’s your experience?

**Comment by screamloud** [comment]
Hey davesc,
Can you please confirm that iOS 18 is supported without any issues?
I have not upgraded to iOS 18 yet, as I want to make sure that it works like iOS 17.
Thanks. :-)

**Comment by davesc63** [comment]
> Hey davesc, Can you please confirm that iOS 18 is supported without any issues? I have not upgraded to iOS 18 yet, as I want to make sure that it works like iOS 17. Thanks. :-)

FFS... read my reply
