### ISSUE TITLE
WA options?

### ISSUE THREAD

**Issue by debonair99** [davesc63/GeoPort#95]
Greetings,
Amazing what you have created here!
I had a question when trying to lock full in for WA. Usually use HMA VPN and it works for any NSW locks (ie. location set to Sydney and locks in for NSW). But I cannot replicate the same for WA and keep getting an error (ie. change location to Perth and try to lock in then error appears). What is the best way around this? Cheers

**Comment by davesc63** [comment]
I provide a NordVPN referral link. So I won’t comment on HMA

7-11 are doing their best to prevent the interstate choppers
