### ISSUE TITLE
iOS 18 Resets Location after a few mins 

### ISSUE THREAD

**Issue by Dannny0117** [davesc63/GeoPort#98]
when using this with iOS 18 it sets the location without issues but then after a few minutes the phone reverts back to the gps location and not the set location. Is there a way to make it just like iOS 17 that wont reset the location?

**Comment by troy341** [comment]
the same thing is happening to me. i tried everything even keeping my phone plugged in to see if it would make a difference but its still resetting

**Comment by davesc63** [comment]
We believe this is "by design" from Apple as part of iOS 18 GA release
They are trying to make it harder to location spoof outside of "development / testing"

**Comment by h4plo84** [comment]
Does 17.7 have similar problem? Anyone tried?

**Comment by screamloud** [comment]
So just to clarify, in iOS 18 the location reverts back to the true location for everyone after setting the fake location, am I correct?

**Comment by mikajx** [comment]
@screamloud affirmative

**Comment by davesc63** [comment]
Correct. This is an ios18 "Feature" that apple has introduced. There is no way around it
